#!/usr/bin/env python
import os
from collections import defaultdict

hosts = {'mill001', 'mill004', 'mill006'}
#, 'mill008', 'mill011', 'mill022', 'mill025', 'mill014', 'mill029'}
user = 'a6915654'
file_location = '/work/a6915654/ZabCT/'
#file_location = '/work/a6915654/ABCast/'
file_wildcard = '*'
extension = "*.*"
get_file = file_location + extension
#destination = './abzabct/'
destination = './ZabCT/'
number_of_rounds = 18

#os.system("rm *" + extension)
for hostname in hosts:
    cmd = "scp " + user + "@" + hostname + ":" + get_file + " " + destination
    print cmd
    os.system(cmd)


