#!/bin/bash
arr=(mill003 mill005 mill006 mill008 mill010 mill011 mill013)
geometry=10x24+10+40
moveToZab="cd /; cd work; cd Zab; cd Adaptation;"
movetZab2Phases="cd /; cd work; cd Zab2Phases;"
movetZabCoinTossing="cd /; cd work; cd ZabCoinTossing; cd Adaptation;"
command="rm -r *.csv"
	for ((i = 0; i < ${#arr[@]}; i++));do
		HOST="${arr[$i]}"
		   ssh -T -o ConnectTimeout=1 -o StrictHostKeychecking=no $HOST <<-ENDEXP
		   $moveToZab
		   nohup $command < /dev/null &
		ENDEXP

	   done
        exit
