#!/bin/bash
#zabbox=(mill001 mill002 mill004 mill006 mill013 mill009 mill016 mill019 mill010 mill020 mill021 mill022 mill024 mill025)
#-agentpath:/home/pg/p13/a6915654/jprofiler9/bin/linux-x64/libjprofilerti.so
#zabbox=(mill001 mill002 mill003 mill004 mill005 mill006 mill007 mill008 mill009 mill010 mill011 mill013 mill014 mill016 mill017 mill019 mill020 mill022 mill025 mill026 mill029 mill024 mill021)
zabbox=(mill001 mill003 mill004 mill005 mill006 mill007 mill010 mill011 mill016 mill017 mill020 mill025 mill029)
#zabbox=(mill001 mill002 mill003 mill004 mill005 mill006 mill007 mill008 mill009 mill010 mill011 mill013 mill014 mill016 mill017)
servers="mill001,mill003,mill004"
#zabbox=(mill001 mill004 mill006 mill008 mill011 mill003 mill002 mill005 mill007 mill009 mill010 mill013 mill017 mill019 mill020)
geometry=(55x6+10-1200 55x6+10-320 55x6+10-120 55x6+10-0 55x6+10-0 55x6+650-1200 55x6+650-320 55x6+650-120 55x6+650-0 55x6+650-0 55x6+1290-320 55x6+1290-120 55x6+1290-0 55x6+1290-0 55x6+1290-0 55x6+1290-0 55x6+1290-0 55x6+1290-0 55x6+1290-0 55x6+1290-0 55x6+1290-0 55x6+1290-0 55x6+1290-0)
protocolName="Zab"
config1="Zab.xml"
config3="ZabCoinTossing.xml"
config4="ZabClientHandler.xml"

clusterSize=3
totalMessages=1000000
numOfClients=10
numbersThreads=20
numberOfMessagesPerClients=$(($totalMessages /$numOfClients))
numberOfMessages=$(($numberOfMessagesPerClients /$numbersThreads))
msgSize=1000
serverLoad=0
warmupRequests=10000
warmupRPerThread=$(($warmupRequests /$numbersThreads))

move="cd /home/pg/p13/a6915654/JGroups/;"
outDir="/home/pg/p13/a6915654/$protocolName/"
output="/home/pg/p13/a6915654/output"
sendTime=100
initiator=${zabbox[$((${#zabbox[@]} - 1))]} 
channelName="Zaspan"
jvmMin="-Xms1000m"
jvmMax="-Xmx3g"
command="java $jvmMin -Djava.net.preferIPv4Stack=true -cp .:./JGroups/dist/jgroups-3.6.0.Final.jar:./JGroups/dist/guava-19.0.jar org.jgroups.protocols.jzookeeper.clustersizezabnew.ZabTestThreads -warmup $warmupRPerThread -load $serverLoad -config $config1 -hosts $servers -name $protocolName -tmessages $totalMessages -nmessages $numberOfMessages -threads $numbersThreads -msgSize $msgSize -outputDir $outDir -numClients $numOfClients -sTime $sendTime -init $initiator -clusterSize $clusterSize -channel $channelName"

for ((i = 0; i < ${#zabbox[@]}; i++));do
    HOST="a6915654@${zabbox[$i]}"
    gnome-terminal --geometry=${geometry[$i]} --title "${zabbox[$i]}" -x bash -c "ssh -t -o ConnectTimeout=1  $HOST '$command; bash'" 
    #ssh -T -o ConnectTimeout=1 -o StrictHostKeychecking=no  $HOST <<-ENDEXP
   # nohup $command > $output${zabbox[$i]}.out 2> $output${zabbox[$i]}.err < /dev/null &
    #exit
#ENDEXP

       sleep 3.0;
   done
exit


