#!/bin/bash
#-agentpath:/home/pg/p13/a6915654/jprofiler9/bin/linux-x64/libjprofilerti.so
#zabbox=(mill001 mill004 mill006 mill003 mill002 mill005 mill007 mill009 mill010 mill013 mill017 mill019 mill020 mill025 mill021 mill029 mill014 mill008 mill011 mill026n mill024 mill022)
zabbox=(mill001 mill002 mill003 mill006 mill008 mill009 mill010 mill011 mill014 mill016 mill017 mill019 mill020)

servers="mill001,mill002,mill003"
geometry=(55x6+10-1200 55x6+10-320 55x6+10-120 55x6+10-0 55x6+10-0 55x6+650-1200 55x6+650-320 55x6+650-120 55x6+650-0 55x6+650-0 55x6+1290-320 55x6+1290-120 55x6+1290-0)
protocolName="Zab";
config1="Zab.xml"


totalMessages=1000000
numOfClients=10
numbersThreads=10
numberOfMessagesPerClients=$(($totalMessages /$numOfClients))
numberOfMessages=$(($numberOfMessagesPerClients /$numbersThreads))
msgSize=1000
serverLoad=0
warmupRequests=10000
waemupRPerThread=$(($warmupRequests /$numbersThreads))

move="cd /home/pg/p13/a6915654/JGroups/;"
outDir="/home/pg/p13/a6915654/$protocolName/"
output="/home/pg/p13/a6915654/output"
sendTime=$1

initiator=${zabbox[$((${#zabbox[@]} - 1))]} 
lastNode=$((${#zabbox[@]} - 1))
jvmMin="-Xms1000m"
jvmMax="-Xmx3g"

command="java $jvmMin -Djava.net.preferIPv4Stack=true -cp .:./JGroups/dist/jgroups-3.6.0.Final.jar:./JGroups/dist/guava-19.0.jar org.jgroups.protocols.jzookeeper.ZabTestThreads -warmup $waemupRPerThread -load $serverLoad -config $config1 -hosts $servers -name $protocolName -tmessages $totalMessages -nmessages $numberOfMessages -threads $numbersThreads -msgSize $msgSize -outputDir $outDir -numClients $numOfClients -sTime $sendTime -init $initiator"


outDir="/home/pg/p13/a6915654/"

for ((i = 0; i < ${#zabbox[@]}; i++));do
    HOST="a6915654@${zabbox[$i]}"
    ssh -T -o ConnectTimeout=1 -o StrictHostKeychecking=no  $HOST <<-ENDEXP
    nohup $command > $output${zabbox[$i]}.out 2> $output${zabbox[$i]}.err < /dev/null &
    exit
ENDEXP
      # gnome-terminal --geometry=${geometry[$i]} --title "${zabbox[$i]}" -x bash -c "ssh -t -o ConnectTimeout=1  a6915654@${zabbox#  [$i]}.ncl.ac.uk '$move$use; bash'"
       sleep 3.0;
   done
exit



