#!/bin/bash
arr=(mill041 mill046 mill040)
#arr=(mill039 mill046 mill040 mill042 mill044)
geometry=10x24+10+40
movetozookeeper="cd /home/pg/p13/a6915654/; cd zookeeper6/"
#movetozookeeper="cd /home/pg/p13/a6915654/; cd zookeeperTest; cd zookeeper"
cleanUpWork="cd /; cd work; cd zookeeper; cd data; rm -rf version-2; cd ..; cd log; rm -rf version-2; cd ..; cd zookeeperlog; rm -r *.*; cd ..; cd latency; rm -r *.*; cd /; cd /home/pg/p13/a6915654; cd zookeeper6/"
command="bin/zkServer.sh stop"
#movetowork="cd /; cd work; cd zookeeper; cd latency;"
#command="rm -r *.*"
if [[ $# < 1 ]]; then
	for ((i = 0; i < ${#arr[@]}; i++));do
		HOST="${arr[$i]}"
		if (( $i >= 0 )); then
		   ssh -T -o ConnectTimeout=1 -o StrictHostKeychecking=no $HOST <<-ENDEXP
		   $movetozookeeper
		   nohup $command > ${arr[$i]}.out 2> ${arr[$i]}.err < /dev/null &
		   $cleanUpWork
 		   gnome-terminal --geometry=10x24+10 --title "${arr[$i]}" "ssh -t -o ConnectTimeout=1 a6915654@${arr[$i]}.ncl.ac.uk " > output.txt 			    2>&1
		    exit
		ENDEXP
		fi
	done
else
	if [ $1 = "kill" ]; then
	   for i in ${arr[@]}; do
               if [ $i != ${arr[0]} ]; then
               	  HOST="a6915654@$i"
                  ssh -t -o ConnectTimeout=1 $HOST 'pkill -u a6915654'
       	       fi
	   done
        fi
fi
exit
